justdial/urls.py
from django.contrib import admin
from django.urls import path
from justdial import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # main page
    path('', views.home),

    # login signup logout page
    path('login', views.login),
    path('signup', views.signup),
    path('logout', views.logout),

    # login signup page data
    path('actionsignup', views.actionsignup),
    path('actionlogin', views.actionlogin),

    # Bussinesses in Main Category Page
    path('category/<int:id>',views.category),

    # Main Bussiness
    path('bussiness/<int:id>',views.bussiness),

    # Edit Profile
    path('edit',views.edit), 
    path('editprofile',views.editprofile),

    # Change Password 
    path('changepassword',views.changepassword),
    path('passwordchange',views.passwordchange),
    
    # Search Bussiness
    path('search',views.search),

    # Comment and rating url 
    path('sharereply',views.sharereply),
    path('updatereply',views.updatereply),

    # Add District 
    path("adddistrict",views.adddistrict),

    # Dashboard Page 
    path("dashboard",views.dashboard),
    path("views",views.views),
    path("EditProfile",views.EditProfile),
    path("ChangePassword",views.ChangePassword),
    path("DashChangePassword",views.DashChangePassword),

    # Add Bussiness 
    
    path('addbussinessdata', views.addbussinessdata),
    path('UpdateBusiness', views.UpdateBusiness),
    
    # Views 
    path("loadmore",views.loadmore),

    # Advertisement
    path("advertisement",views.advertisement),
    path("advdata",views.advdata),

    # Gallery
    path("Gallery",views.gallery),
    path("galleryimg",views.galleryimg),
    path("galdelete/<int:id>",views.galdelete),

    # Bussiness Lead
    path("leadbussiness",views.leadbussiness),

    # Appointment
    path("appointment",views.appointments),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AddBussiness/models.py
from django.db import models
from Category.models import Category

class Business(models.Model):
    title = models.CharField(max_length=100)
    address = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    email = models.CharField(max_length=50, default='')
    state = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    contact_number = models.CharField(max_length=50)
    open_until = models.CharField(max_length=100)
    experience = models.CharField(max_length=100)
    timing = models.CharField(max_length=100)
    service = models.TextField()
    overview = models.TextField()
    youtube = models.CharField(max_length=200, default='')
    image = models.ImageField(upload_to='business_images/')

class Search(models.Model):
    business_id = models.IntegerField() 
    city = models.CharField(max_length=100)

class Message(models.Model):
    business_id = models.IntegerField() 
    user =  models.CharField(max_length=200)
    email =  models.CharField(max_length=100)
    rating = models.IntegerField()
    message =  models.TextField()


class Gallery(models.Model):
    business_id = models.IntegerField()
    image = models.ImageField(upload_to='business_gallery/')

class Lead(models.Model):
    business_id = models.IntegerField() 
    user =  models.CharField(max_length=200)
    email =  models.CharField(max_length=100)
    search = models.CharField(max_length=200)
    location = models.CharField(max_length=200)

class Adv(models.Model):
    business_email = models.CharField(max_length=100)
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    option3 = models.CharField(max_length=100)
    option4 = models.CharField(max_length=100)
    image = models.ImageField(upload_to='advertisement_images/')

Category/models.py
from django.db import models

class Category(models.Model):
    category = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.category

Login/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    phone = models.IntegerField()
    BUSINESS_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]
    bussiness = models.CharField(max_length=3, choices=BUSINESS_CHOICES, default='no')
    
class History(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

Category/views.py
from django.shortcuts import render

# Create your views here.

Login/views.py
from django.shortcuts import render

# Create your views here.

templates/EditProfile.html
{% extends "master1.html" %}
{% block maincontent %}
    {% if userdetails %}
            <center><label style="font-size:20px;font-family:serif"><b>Edit Your Profile</b></label></center><br><br>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success text-center">{{ message }}</div>
                    {% elif message.tags == 'warning' %}
                        <div class="alert alert-danger text-center">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <form method="post" action="DashEditProfile">
                {% csrf_token %}
                <label>Name:</label>
                <input type="text" value="{{userdetails.name}}" name="name" class="form-control"><br>
                <label>Number:</label>
                <input type="number" value="{{userdetails.phone}}" name="phone" class="form-control"><br>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        {% endif %}
    
{% endblock maincontent %}

templates/category.html
{% extends "master.html" %}
{% load static %}
{% block main %}
   
    <div class="container"  style="margin-top:100px">
        <div class="row">
            <div class="col-lg-12">
                <label style="font-size:30px"><b>Bussiness in {{catname}}:</b></label>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                {% for business in businesses %}
                    <div class="row" style="border-radius:20px;margin-top:20px;border:1px solid #d9d9d9;padding:20px 10px">
                        
                        <div class="col-lg-4 col-sm-5 col-md-5">
                            <a href="/bussiness/{{ business.id }}"><img src="{{ business.image.url }}" class="img-fluid"> </a>
                        </div>
                        <div class="col-lg-8 col-sm-7 col-md-7">
                            <a href="/bussiness/{{ business.id }}"><label style="font-size:20px;cursor:pointer;font-family:serif;color:black"><b>{{ business.title }} </b></label></a>
                            <br>
                            <label>{{ business.address }}</label><br>
                            
                            <label>Location : {{ business.district }}, {{ business.state }}</label><br>
                            
                            <button class="w3-btn btn-success shownumber" id="{{business.id}}" rel="{{ business.contact_number }}"><i class="bx bx-phone" style="cursor: pointer; font-size: 20px;"></i> <span class="hidenumber"  id="shownumber-{{business.id}}" >Show Number</span></button>
                            <a href="/bussiness/{{ business.id }}"><button class="w3-btn btn-primary">Quick View</button></a>
                        </div>                            
                                        
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-4 advertisementdiv" style="margin-top:20px">
                {% if advertisement %}
                    <div id="slideshow" class="img-fluid">
                        {% for ad in advertisement %}
                            {% if ad.option2 %}
                                <img src="{{ ad.image.url }}" class="slide-img img-fluid" style="display:none;">
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
        </div>
        
    </div>
    <script>
        $(document).on("click",".shownumber",function(){
            $(".hidenumber").text("Show Number");
            var number = $(this).attr("rel");
            var id = $(this).attr("id");
            $("#shownumber-"+id).text(number);
        });

        const slides = document.querySelectorAll('#slideshow .slide-img');
        let currentSlide = 0;
        function showSlide(index) {
            slides.forEach((slide, i) => {
                slide.style.display = (i === index) ? 'block' : 'none';
            });
        }
        function nextSlide() {
            currentSlide = (currentSlide + 1) % slides.length;
            showSlide(currentSlide);
        }
        showSlide(currentSlide);
        setInterval(nextSlide, 3000);
    
        </script>
        
{% endblock main %}

templates/footer.html
<style>
    /*footer*/
.col_white_amrc { color:#FFF;}
footer { width:100%; background-color:#263238; min-height:250px; padding:10px 0px 25px 0px ;}
.pt2 { padding-top:40px ; margin-bottom:20px ;}
footer p { font-size:13px; color:#CCC; padding-bottom:0px; margin-bottom:8px;}
.mb10 { padding-bottom:15px ;}
.footer_ul_amrc { margin:0px ; list-style-type:none ; font-size:14px; padding:0px 0px 10px 0px ; }
.footer_ul_amrc li {padding:0px 0px 5px 0px;}
.footer_ul_amrc li a{ color:#CCC;}
.footer_ul_amrc li a:hover{ color:#fff; text-decoration:none;}
.fleft { float:left;}
.padding-right { padding-right:10px; }

.footer_ul2_amrc {margin:0px; list-style-type:none; padding:0px;}
.footer_ul2_amrc li p { display:table; }
.footer_ul2_amrc li a:hover { text-decoration:none;}
.footer_ul2_amrc li i { margin-top:5px;}

.bottom_border { border-bottom:1px solid #323f45; padding-bottom:20px;}
.foote_bottom_ul_amrc {
	list-style-type:none;
	padding:0px;
	display:table;
	margin-top: 10px;
	margin-right: auto;
	margin-bottom: 10px;
	margin-left: auto;
}
.foote_bottom_ul_amrc li { display:inline;}
.foote_bottom_ul_amrc li a { color:#999; margin:0 12px;}

.social_footer_ul { display:table; margin:15px auto 0 auto; list-style-type:none;  }
.social_footer_ul li { padding-left:20px; padding-top:10px; float:left; }
.social_footer_ul li a { color:#CCC; border:1px solid #CCC; padding:8px;border-radius:50%;}
.social_footer_ul li i {  width:20px; height:20px; text-align:center;}
</style>
<footer class="footer" style="margin-top:50px">
    <div class="container bottom_border">
    <div class="row">
    <div class=" col-sm-4 col-md col-sm-4  col-12 col">
    <h5 class="headin5_amrc col_white_amrc pt2">About us</h5>
    <!--headin5_amrc-->
    <p class="mb10">
        Discover local businesses with ease on Quick Connect! From restaurants and salons to plumbers and electricians, find detailed information, reviews, and contact details to connect with reliable services near you. Your one-stop local search engine!
    </p>
    
    </div>
    
    
    <div class=" col-sm-4 col-md  col-6 col">
    <h5 class="headin5_amrc col_white_amrc pt2">Some Categories</h5>
    <!--headin5_amrc-->
    <ul class="footer_ul_amrc">
        {% if categoriesfooter %}
            {% for cat in categoriesfooter %}
                <li><a href="/category/{{cat.id}}">{{cat.category}}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
    <!--footer_ul_amrc ends here-->
    </div>
    
    
    <div class=" col-sm-4 col-md  col-6 col">
    <h5 class="headin5_amrc col_white_amrc pt2">Some Bussinesses</h5>
    <!--headin5_amrc-->
    <ul class="footer_ul_amrc">
        {% if busssinessfooter %}
            {% for bus in busssinessfooter %}
                <li><a href="/bussiness/{{bus.id}}">{{bus.title}}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
    <!--footer_ul_amrc ends here-->
    </div>
    
    
    <div class=" col-sm-4 col-md  col-12 col">
    <h5 class="headin5_amrc col_white_amrc pt2">Social Links</h5>
    <!--headin5_amrc ends here-->
    
    <ul class="footer_ul2_amrc">
        <li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Follow me on <a href="https://x.com/Keshav_Bansal01">Twitter</a></p></li>
        <li><a href="#"><i class="fab fa-facebook fleft padding-right"></i> </a><p>Follow me on <a href="https://www.facebook.com/profile.php?id=100078367444987">Facebook</a></p></li>
        <li><a href="#"><i class="fab fa-instagram fleft padding-right"></i> </a><p>Follow me on <a href="https://www.instagram.com/keshavbansaltskb/">Instagram</a></p></li>
        <li><a href="#"><i class="fab fa-linkedin fleft padding-right"></i> </a><p>Follow me on <a href="https://www.linkedin.com/in/keshav-bansal-875b38221/">LinkedIn</a></p></li>
    </ul>
    <!--footer_ul2_amrc ends here-->
    </div>
    </div>
    </div>
    
    
    <div class="container" style="margin-top:10px">
    <!--foote_bottom_ul_amrc ends here-->
    <p class="text-center">Copyright @2024 | Designed With by <a href="http://keshav.skillhoard.com/">keshav.skillhoard.com</a></p>
    <p class="text-center"><i class="fa fa-location-arrow"></i> Mukta parasad colony, Bikaner, Rajasthan, India</p>
    <p class="text-center"><i class="fa fa-phone"></i>  +91-9358391857  </p>
    <p class="text-center"><i class="fa fa fa-envelope"></i> keshav@skillhoard.com </p>
    <ul class="social_footer_ul">
        <li><a href="https://www.facebook.com/profile.php?id=100078367444987"><i class="fab fa-facebook-f"></i></a></li>
        <li><a href="https://x.com/Keshav_Bansal01"><i class='bx bx-x'></i></a></li>
        <li><a href="https://www.linkedin.com/in/keshav-bansal-875b38221/"><i class="fab fa-linkedin"></i></a></li>
        <li><a href="https://www.instagram.com/keshavbansaltskb/"><i class="fab fa-instagram"></i></a></li>
    </ul>
    <!--social_footer_ul ends here-->
    </div>
    
    </footer>
    <script>
        AOS.init();
    </script>
</body>
</html>

templates/gallery.html
{% extends "master1.html" %}
{% block maincontent %}
<div class="modal fade" id="GalleryModel">
    <div class="modal-dialog  modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title"> <b>{{bus.title}}</b></h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
        <div class="modal-body">
           <img src="" id="imgshowgal" class="img-fluid">
        </div>
      </div>
    </div>
</div>
<script>
    $(document).on("click",".showgalleryimage",function(){
        var src = $(this).attr("src");
        $("#imgshowgal").attr("src",src);
    });

</script>
    <div class="row">
        <div class="col-lg-12">
            <center><label style="font-size:20px;font-weight:bold">Gallery </label></center>
            <br>
            {% if messages %}
                {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success text-center">{{ message }}</div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-warning text-center">{{ message }}</div>
                {% endif %}
                {% endfor %}
            
            {% endif %}
            <form method="post" action="/galleryimg"  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label  style="font-size:20px"><b>Upload Image</b></label>
                    <input type="file" class="form-control-file" id="image" name="image" required>
                </div>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
    <div class="row" style="margin-top:20px">
        {% if gallery %}
            <div class="col-lg-12" style="margin-bottom:20px">
                <center><label style="font-size:20px;font-weight:bold">Your gallery Images</label></center>
            </div>
            {% for img in gallery %}
                <div class="col-lg-4">
                    <img src="{{ img.image.url }}"  data-toggle="modal" data-target="#GalleryModel"  class="img-fluid showgalleryimage" style="cursor:pointer">
                    <div class="text-center">
                        <br>
                        <a href="/galdelete/{{img.id}}">
                            <button class="btn btn-danger">Delete</button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-lg-12">
                <center><label style="font-size:20px;font-weight:bold">Your gallery is empty</label></center>
            </div>
        {% endif %}
    </div>
{% endblock maincontent %}

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title class="headtitle">JustDial</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- W3 CSS Link -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!-- Bootstrap Links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Font Awesome link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Box Icon Link -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- Footer link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- AOS animation -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <style>
        body{
            scroll-behavior: smooth;
        }
        .navbar-toggler {
            background-color: white; /* New background color */
            border-color: #000; /* New border color, if needed */
            /* Other styles you want to apply */
        }
        .navbar-toggler-icon{
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%23000000' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");
        }
        nav {
            background-color: #f2f2f2;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Add shadow effect */
            z-index: 1000; /* Ensure the nav stays above other content */
        }
        .advertisementdiv{
            display:block;
        }
        @media only screen and (max-width: 1000px) {
            .advertisementdiv{
                display:none;
            }
        }
    </style>
    <script>
        $(document).ready(function(){
            
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var lat = position.coords.latitude;
                    var lon = position.coords.longitude;
                    var url = 'https://nominatim.openstreetmap.org/reverse?format=json&lat=' + lat + '&lon=' + lon + '&zoom=10&addressdetails=1';
                    $.getJSON(url, function(data) {
                        var address = data.address;
                        $('.iplocation').val(address.city || address.town || address.village || '');
                    });
                }, function(error) {
                    console.error('Error occurred. Error code: ' + error.code + ', Message: ' + error.message);
                    $('.iplocation').attr('placeholder', 'Location');
                });
            } else {
                console.error('Geolocation is not supported by this browser.');
                $('.iplocation').attr('placeholder', 'Location');
            }
        });
    </script>
</head>
<body>
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-dialog-centered ">
          <div class="modal-content">
          
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Logout Confirmation</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            
            <!-- Modal body -->
            <div class="modal-body">
                <p>Are you sure you want to logout?</p>
            </div>
            
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <a class="nav-link" href="/logout"><button type="submit" class="btn btn-primary">Logout</button></a>
            </div>
            
          </div>
        </div>
      </div>
      
    </div>
    
<nav class="navbar navbar-expand-md fixed-top">
  <a class="navbar-brand" href="/">
    <label style="color:blue;font-size:25px;font-family:serif;cursor:pointer">Quick<span style="color:red">Connect</span></label>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mx-auto">
        <li class="nav-item">
            <form method="post" action="/search">
                {% csrf_token %}
                <div class="input-group" style="margin: 10px;">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-map-marker"></i></span>
                    </div>
                    <input type="text" class="form-control iplocation" name="location" placeholder="Location" value="" required>
                    <input type="text" class="form-control" name="business" style="margin-left:10px" placeholder="Search any Business" required>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit"  style="margin-left:10px" id="search-button">Search</button>
                    </div>
                </div>
            </form>
        </li>
    </ul>    
    <ul class="navbar-nav ml-auto">
        {% if user %}
            <li>
                <a class="nav-link" href="/dashboard">
                    <button class="w3-button w3-white w3-border">Dashboard</button>
                </a>
            </li>
            <li>
                <a class="nav-link">
                    <button class="w3-btn btn-danger" data-toggle="modal" data-target="#myModal">Logout</button>
                </a>
            </li>
        {% else %}
            <li>
                <button class="w3-btn btn-primary nav-link">
                    <a  href="/login"  style="color:white;text-decoration:none">Login</a> / 
                    <a href="/signup"  style="color:white;text-decoration:none">Signup</a>
                </button>
            </li>  
        {% endif %}
        </li>    
    </ul>
  </div>  
</nav>
</body>
</html>

templates/index.html
{% extends "master.html" %}
{% block main %}
    <style>
        .categoriess{
            width:10%;
            cursor:pointer;
            margin-top:20px
        }
        .catimg{
            width:80px;
            height:70px;
            border: 1px solid #999;
            border-radius :10px;
            padding:10px;
        }
        .categoriess:hover .catimg{
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        .catname{
            color:black;
            margin-right:40px;
            font-weight:400;
            font-family:sans-serif;
            width:60px;
            font-size:16px;
            cursor:pointer;
            margin-top:5px;
            text-align:center;
        }
        @media only screen and (max-width:900px) {
            .categoriess{
                width:15%;
            }
        }
        @media only screen and (max-width: 600px) {
            .categoriess{
                width:20%;
            }
            .catname{
                font-size:14px;
                margin-right:30px;
            }
        }
    </style>
    
    <div class="container" style="margin-top:100px">
        <div class="row">
            <div class="col-lg-12">
                <label style="font-size:20px;font-family:serif"><b>Search across <span style="color:blue">Bussiness</span></b></label><br>
            </div>
            
            <div class="col-lg-6 col-sm-12 col-md-9">
                <form method="post" action="search">
                    {% csrf_token %}
                    <div class="input-group" style="margin-top: 10px;">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-map-marker"></i></span>
                        </div>
                        <input type="text" class="form-control iplocation" name="location" placeholder="Location" required>
                        <input type="text" style="margin-left:10px" name="business" class="form-control" placeholder="Search any Bussiness" required>
                        <button  style="margin-left:10px"  class="w3-btn btn-primary" type="submit" id="search-button"> Search</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-md-3">
            </div>
            
        </div>
        <div class="row"  style="margin-top: 20px;">
            
            {% for category in cat %}
                <div class="categoriess">
                    <a href="/category/{{category.id}}"><img src="{{ category.image.url }}" class="img-fluid catimg"></a>
                    <br>
                    <a href="/category/{{category.id}}"><center><label class="catname">{{ category.category }}</label></center></a>
                </div>
            {% endfor %}
            
        </div>
        <div class="row" style="margin-top:50px">
            {% for category in cat %}
            <div class="col-lg-6" style="padding:10px"   data-aos="fade-up" data-aos-duration="2000">
                <div style="margin-top:20px;border:1px solid #d9d9d9;padding:10px">
                    <div class="">
                        <a href="/category/{{ category.id }}" style="color:black;margin-left:10px;font-size:20px;font-family:serif;font-weight:bold">
                            <label style="cursor:pointer;margin-bottom:10px;line-">{{ category.category }}</label>
                        </a>
                    </div>
                    <div class="row">
                        {% for business in category.business_set.all|slice:":2"  %}
                        <div class="col-6">
                            <a href="/bussiness/{{ business.id }}"><img src="{{ business.image.url }}" class="img-fluid" style="cursor:pointer" >
                            <br><br>
                            <center><label style="cursor:pointer;color:black">{{ business.title }}</label></center></a>
                        </div>
                        {% empty %}
                        <p style="margin-left:30px">No businesses available for this category.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>

    </div>
    
{% endblock main %}

templates/leadbussiness.html
{% extends "master1.html" %}
{% block maincontent %}
    {% if leadbussiness %}
        <div class="row">
            <div class="col-lg-12">
                <label style="font-size:20px;font-family:serif"><b>
                    "People have searched for information related to your business."
                </b></label>
            </div>
            <table class="table table-striped table-hover" style="margin-top:20px">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Location</th>
                    <th>Search</th>
                </tr>
                {% for lead in leadbussiness %}
                    <tr>
                        <td>{{lead.user}}</td>
                        <td>{{lead.email}}</td>
                        <td>{{lead.location}}</td>
                        <td>{{lead.search}}</td>
                    </tr>
                {% endfor %}
            </table>
            <div class="col-lg-12">
                {% if leadbussiness.has_previous %}
                    <a href="?page={{leadbussiness.previous_page_number}}"><button class="btn btn-primary">Previous</button></a>
                {% endif %}
                {% if leadbussiness.has_next %}
                    <a href="?page={{leadbussiness.next_page_number}}"><button class="btn btn-primary" style="float:right">Next</button></a>
                {% endif %}
            </div>
        </div>
    {% else %}
    <label style="font-size:20px;font-family:serif"><b>
        "No searches related to your business have been made."
    </b></label>
    {% endif %}
    
{% endblock maincontent %}

templates/master.html
{% include "header.html" %}

{% block main %}

{% endblock main %}

{% include "footer.html" %}

templates/password.html
{% extends "master.html" %}
{% block main %}
    <div class="container"  style="margin-top:100px">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <center><label style="font-size:20px;font-family:serif"><b>Change Your Password</b></label></center><br><br>
                {% if messages %}
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success text-center">{{ message }}</div>
                    {% elif message.tags == 'warning' %}
                        <div class="alert alert-danger text-center">{{ message }}</div>
                    {% endif %}
                    {% endfor %}
                
                {% endif %}
                <form method="post" action="/passwordchange">
                    {% csrf_token %}
                    <label>Current password:</label>
                    <input type="password"  name="cp" class="form-control"><br>
                    <label>New password:</label>
                    <input type="password"  name="np" class="form-control"><br>
                    <label>Retype password:</label>
                    <input type="password"  name="rp" class="form-control"><br>
                    <input type="submit" class="w3-btn btn-primary" value="Submit">
                </form>
                
                
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
    
{% endblock main %}

    